POS_START = -1.0
MAX_ACC = 1.0
MIN_ACC = -2.0
MAX_ALLOWED_VEL = 1.0
VEL_START = MAX_ALLOWED_VEL
DT = 0.001
NUM_OBSERVATION_VARIABLES = 1

# NN parameters
STDDEV = 0.01  # Standard deviation of initial weight distribution
LEARNING_PARAMETER = 0.01
